name = "lumatrix"
version = "1.0.0"
description = "Numerical linear algebra routines in pure Gleam"
licences = ["Apache-2.0"]

repository = { type = "github", user = "L0stInFades", repo = "Lumatrix" }
links = [{ title = "GitHub", href = "https://github.com/L0stInFades/Lumatrix" }]

[dependencies]
gleam_stdlib = ">= 1.0.0 and < 2.0.0"

[dev_dependencies]
gleeunit = ">= 1.0.0 and < 2.0.0"
