//// This module is generated by tools/generate_weird_cases.py.
//// Regenerate it after changing the Python fixture definitions.

pub type MatrixCase {
  MatrixCase(name: String, rows: List(List(Float)))
}

pub type VectorCase {
  VectorCase(name: String, data: List(Float))
}

pub type SolveCase {
  SolveCase(
    name: String,
    rows: List(List(Float)),
    rhs: List(Float),
    solution: List(Float),
  )
}

pub type LeastSquaresCase {
  LeastSquaresCase(
    name: String,
    rows: List(List(Float)),
    rhs: List(Float),
    solution: List(Float),
    residual_norm: Float,
  )
}

pub type SvdCase {
  SvdCase(name: String, rows: List(List(Float)), singular_values: List(Float))
}

pub type SymmetricEigenCase {
  SymmetricEigenCase(
    name: String,
    rows: List(List(Float)),
    eigenvalues: List(Float),
  )
}

pub type CholeskyCase {
  CholeskyCase(name: String, rows: List(List(Float)), lower: List(List(Float)))
}

pub fn square_cases() -> List(MatrixCase) {
  [
    MatrixCase(name: "identity_3", rows: [
      [1.0, 0.0, 0.0],
      [0.0, 1.0, 0.0],
      [0.0, 0.0, 1.0],
    ]),
    MatrixCase(name: "scaled_diagonal_4", rows: [
      [0.001, 0.0, 0.0, 0.0],
      [0.0, -2.0, 0.0, 0.0],
      [0.0, 0.0, 5.0, 0.0],
      [0.0, 0.0, 0.0, 11.0],
    ]),
    MatrixCase(name: "hilbert_4", rows: [
      [1.0, 0.5, 0.333333333333333, 0.25],
      [0.5, 0.333333333333333, 0.25, 0.2],
      [0.333333333333333, 0.25, 0.2, 0.166666666666667],
      [0.25, 0.2, 0.166666666666667, 0.142857142857143],
    ]),
    MatrixCase(name: "vandermonde_3", rows: [
      [1.0, -2.0, 4.0],
      [1.0, 0.5, 0.25],
      [1.0, 3.0, 9.0],
    ]),
    MatrixCase(name: "nearly_singular_3", rows: [
      [1.0, 1.0, 1.0],
      [1.0, 1.000001, 1.0],
      [1.0, 1.0, 1.000002],
    ]),
    MatrixCase(name: "alternating_sign_3", rows: [
      [1.0, -3.0, 5.0],
      [-2.0, 4.0, -6.0],
      [3.0, -5.0, 7.0],
    ]),
    MatrixCase(name: "nonsymmetric_3", rows: [
      [0.0, 2.0, -1.0],
      [3.0, 5.0, 4.0],
      [1.0, -2.0, 6.0],
    ]),
    MatrixCase(name: "permutation_scaled_4", rows: [
      [0.0, 0.0, 3.0, 0.0],
      [2.0, 0.0, 0.0, 0.0],
      [0.0, -5.0, 0.0, 0.0],
      [0.0, 0.0, 0.0, 7.0],
    ]),
    MatrixCase(name: "tridiagonal_5", rows: [
      [2.5, -1.0, 0.0, 0.0, 0.0],
      [-0.75, 2.75, -0.9, 0.0, 0.0],
      [0.0, -0.8, 3.0, -0.8, 0.0],
      [0.0, 0.0, -0.85, 3.25, -0.7],
      [0.0, 0.0, 0.0, -0.9, 3.5],
    ]),
    MatrixCase(name: "rank_one_plus_diag_4", rows: [
      [1.5, 1.0, 1.0, 1.0],
      [1.0, 2.5, 1.0, 1.0],
      [1.0, 1.0, 3.5, 1.0],
      [1.0, 1.0, 1.0, 4.5],
    ]),
    MatrixCase(name: "negative_mix_3", rows: [
      [-4.0, 2.0, 0.5],
      [1.0, -3.0, 2.0],
      [0.25, -1.0, -2.0],
    ]),
    MatrixCase(name: "companion_like_3", rows: [
      [0.0, 1.0, 0.0],
      [0.0, 0.0, 1.0],
      [-6.0, 11.0, -6.0],
    ]),
  ]
}

pub fn spd_cases() -> List(MatrixCase) {
  [
    MatrixCase(name: "spd_2_random", rows: [
      [2.57857519355649, 0.591224433995469],
      [0.591224433995469, 1.3469368368591],
    ]),
    MatrixCase(name: "spd_3_random", rows: [
      [1.58617058046422, 0.166608092706715, 0.736524910353797],
      [0.166608092706715, 2.94084242425351, 1.78058216122976],
      [0.736524910353797, 1.78058216122976, 3.33591393116512],
    ]),
    MatrixCase(name: "spd_4_random", rows: [
      [
        7.78313055712357,
        -2.34729553561836,
        0.715360413911937,
        -5.58859122658511,
      ],
      [-2.34729553561836, 5.06694293140312, 1.3763394219514, 3.10586171553665],
      [0.715360413911937, 1.3763394219514, 3.26605432001826, -0.256186127653957],
      [
        -5.58859122658511,
        3.10586171553665,
        -0.256186127653957,
        7.16616890934777,
      ],
    ]),
    MatrixCase(name: "hilbert_spd_3", rows: [
      [1.05, 0.5, 0.333333333333333],
      [0.5, 0.383333333333333, 0.25],
      [0.333333333333333, 0.25, 0.25],
    ]),
    MatrixCase(name: "laplacian_spd_5", rows: [
      [2.2, -1.0, 0.0, 0.0, 0.0],
      [-1.0, 2.2, -1.0, 0.0, 0.0],
      [0.0, -1.0, 2.2, -1.0, 0.0],
      [0.0, 0.0, -1.0, 2.2, -1.0],
      [0.0, 0.0, 0.0, -1.0, 2.2],
    ]),
  ]
}

pub fn tall_cases() -> List(MatrixCase) {
  [
    MatrixCase(name: "tall_vandermonde_4x2", rows: [
      [1.0, -1.0],
      [1.0, 0.0],
      [1.0, 1.0],
      [1.0, 2.0],
    ]),
    MatrixCase(name: "tall_poly_5x3", rows: [
      [1.0, -2.0, 4.0],
      [1.0, -0.5, 0.25],
      [1.0, 0.25, 0.0625],
      [1.0, 1.5, 2.25],
      [1.0, 3.0, 9.0],
    ]),
    MatrixCase(name: "tall_mixed_4x3", rows: [
      [1.0, -1.0, 2.0],
      [2.0, 0.0, -1.0],
      [3.0, 1.0, 0.5],
      [4.0, 2.0, 3.0],
    ]),
    MatrixCase(name: "tall_near_collinear_5x2", rows: [
      [1.0, 1.0],
      [2.0, 2.0001],
      [3.0, 3.0004],
      [4.0, 4.0009],
      [5.0, 5.0016],
    ]),
  ]
}

pub fn stationary_cases() -> List(MatrixCase) {
  [
    MatrixCase(name: "dd_2", rows: [[8.0, -2.0], [-2.0, 5.0]]),
    MatrixCase(name: "dd_3", rows: [
      [8.0, 3.0, -1.0],
      [1.0, 6.0, 2.0],
      [-1.0, -4.0, 11.0],
    ]),
    MatrixCase(name: "dd_4", rows: [
      [9.0, -1.0, 1.0, -3.0],
      [4.0, 14.0, -2.0, 1.0],
      [-4.0, 0.0, 15.0, 4.0],
      [-2.0, 3.0, -2.0, 15.0],
    ]),
  ]
}

pub fn eigen_cases() -> List(MatrixCase) {
  [
    MatrixCase(name: "diagonal_distinct_3", rows: [
      [7.0, 0.0, 0.0],
      [0.0, -2.0, 0.0],
      [0.0, 0.0, 0.5],
    ]),
    MatrixCase(name: "symmetric_2", rows: [[2.0, 1.0], [1.0, 2.0]]),
    MatrixCase(name: "symmetric_3", rows: [
      [4.0, 1.0, 2.0],
      [1.0, 3.0, 0.0],
      [2.0, 0.0, 2.0],
    ]),
    MatrixCase(name: "rotation_2", rows: [[0.0, -1.0], [1.0, 0.0]]),
    MatrixCase(name: "upper_triangular_3", rows: [
      [4.0, 2.0, -1.0],
      [0.0, 3.0, 5.0],
      [0.0, 0.0, -2.0],
    ]),
    MatrixCase(name: "hessenberg_4", rows: [
      [3.0, 2.0, 1.0, 0.0],
      [1.0, 4.0, -1.0, 2.0],
      [0.0, -2.0, 1.0, 1.0],
      [0.0, 0.0, 3.0, 2.0],
    ]),
  ]
}

pub fn vector_cases() -> List(VectorCase) {
  [
    VectorCase(name: "zero_3", data: [0.0, 0.0, 0.0]),
    VectorCase(name: "tiny_large_4", data: [1.0e-9, -1_000_000.0, 3.5, -0.0002]),
    VectorCase(name: "alternating_5", data: [1.0, -2.0, 3.0, -4.0, 5.0]),
    VectorCase(name: "dense_3", data: [2.5, -4.0, 0.125]),
    VectorCase(name: "almost_axis_3", data: [1.0, 1.0e-8, -1.0e-8]),
  ]
}

pub fn solve_oracles() -> List(SolveCase) {
  [
    SolveCase(
      name: "solve_spd_2",
      rows: [[3.0, 1.0], [1.0, 2.0]],
      rhs: [9.0, 8.0],
      solution: [2.0, 3.0],
    ),
    SolveCase(
      name: "solve_nonsymmetric_3",
      rows: [[4.0, -2.0, 1.0], [1.0, 6.0, -2.0], [1.0, 1.0, 5.0]],
      rhs: [1.0, -3.0, 7.0],
      solution: [-0.109489051094891, -0.00729927007299273, 1.42335766423358],
    ),
    SolveCase(
      name: "solve_spd_4",
      rows: [
        [
          5.93842952563932,
          2.52802913902909,
          -0.896618309271697,
          2.61495339693931,
        ],
        [
          2.52802913902909,
          6.85791003583977,
          -1.04792501200604,
          0.112321930695349,
        ],
        [
          -0.896618309271697,
          -1.04792501200604,
          6.22639628066103,
          2.18679386982333,
        ],
        [2.61495339693931, 0.112321930695349, 2.18679386982333, 7.5963715801036],
      ],
      rhs: [1.5, -2.0, 0.25, 3.0],
      solution: [
        0.258321636540901,
        -0.409704789255891,
        -0.112586684991458,
        0.344470203562128,
      ],
    ),
  ]
}

pub fn least_squares_oracles() -> List(LeastSquaresCase) {
  [
    LeastSquaresCase(
      name: "least_squares_vandermonde_5x3",
      rows: [
        [1.0, -2.0, 4.0],
        [1.0, -0.5, 0.25],
        [1.0, 0.25, 0.0625],
        [1.0, 1.5, 2.25],
        [1.0, 3.0, 9.0],
      ],
      rhs: [4.1, 1.2, 0.9, 2.8, 8.7],
      solution: [0.883874111883448, 0.0595771239985974, 0.844760219218373],
      residual_norm: 0.171427044661326,
    ),
    LeastSquaresCase(
      name: "least_squares_mixed_4x2",
      rows: [[1.0, -2.0], [2.0, 1.0], [3.0, 0.5], [4.0, 3.0]],
      rhs: [-1.0, 2.5, 4.0, 8.0],
      solution: [1.11009174311927, 1.08868501529052],
      residual_norm: 0.872183102286654,
    ),
  ]
}

pub fn svd_oracles() -> List(SvdCase) {
  [
    SvdCase(
      name: "svd_tall_4x3",
      rows: [
        [1.0, -1.0, 2.0],
        [2.0, 0.0, -1.0],
        [3.0, 1.0, 0.5],
        [4.0, 2.0, 3.0],
      ],
      singular_values: [6.41448547262606, 2.59795685736589, 1.53459971612625],
    ),
    SvdCase(
      name: "svd_wide_2x4",
      rows: [[1.0, -2.0, 3.0, 0.5], [4.0, 1.0, -1.0, 2.0]],
      singular_values: [4.69041575982343, 3.77491721763537],
    ),
    SvdCase(
      name: "svd_near_rank_one_3x2",
      rows: [[1.0, 1.0001], [2.0, 2.0001], [3.0, 3.0004]],
      singular_values: [5.29178610398778, 9.81927901201962e-5],
    ),
  ]
}

pub fn symmetric_eigen_oracles() -> List(SymmetricEigenCase) {
  [
    SymmetricEigenCase(
      name: "eigen_symmetric_2",
      rows: [[2.0, 1.0], [1.0, 2.0]],
      eigenvalues: [1.0, 3.0],
    ),
    SymmetricEigenCase(
      name: "eigen_symmetric_3",
      rows: [[4.0, 1.0, 2.0], [1.0, 3.0, 0.0], [2.0, 0.0, 2.0]],
      eigenvalues: [0.638531233814174, 2.83255080889146, 5.52891795729436],
    ),
    SymmetricEigenCase(
      name: "eigen_spd_4",
      rows: [
        [
          7.78313055712357,
          -2.34729553561836,
          0.715360413911937,
          -5.58859122658511,
        ],
        [-2.34729553561836, 5.06694293140312, 1.3763394219514, 3.10586171553665],
        [
          0.715360413911937,
          1.3763394219514,
          3.26605432001826,
          -0.256186127653957,
        ],
        [
          -5.58859122658511,
          3.10586171553665,
          -0.256186127653957,
          7.16616890934777,
        ],
      ],
      eigenvalues: [
        1.61509455532764,
        1.97824817813467,
        5.06728726457298,
        14.6216667198574,
      ],
    ),
  ]
}

pub fn cholesky_oracles() -> List(CholeskyCase) {
  [
    CholeskyCase(
      name: "cholesky_spd_2",
      rows: [
        [2.57857519355649, 0.591224433995469],
        [0.591224433995469, 1.3469368368591],
      ],
      lower: [[1.60579425629702, 0.0], [0.36818193344323, 1.10062659460196]],
    ),
    CholeskyCase(
      name: "cholesky_spd_3",
      rows: [
        [1.58617058046422, 0.166608092706715, 0.736524910353797],
        [0.166608092706715, 2.94084242425351, 1.78058216122976],
        [0.736524910353797, 1.78058216122976, 3.33591393116512],
      ],
      lower: [
        [1.25943264228946, 0.0, 0.0],
        [0.132288212257105, 1.70977842223819, 0.0],
        [0.584806908779896, 0.9961636423754, 1.41476952476995],
      ],
    ),
    CholeskyCase(
      name: "cholesky_spd_4",
      rows: [
        [
          7.78313055712357,
          -2.34729553561836,
          0.715360413911937,
          -5.58859122658511,
        ],
        [-2.34729553561836, 5.06694293140312, 1.3763394219514, 3.10586171553665],
        [
          0.715360413911937,
          1.3763394219514,
          3.26605432001826,
          -0.256186127653957,
        ],
        [
          -5.58859122658511,
          3.10586171553665,
          -0.256186127653957,
          7.16616890934777,
        ],
      ],
      lower: [
        [2.78982625930784, 0.0, 0.0, 0.0],
        [-0.841376959510278, 2.08782847557177, 0.0, 0.0],
        [0.256417549847502, 0.762554615494053, 1.61827526043538, 0.0],
        [
          -2.00320403750578,
          0.680329830635309,
          -0.161479394334336,
          1.63230457336291,
        ],
      ],
    ),
  ]
}
